### ISSUE TITLE
ctrl+f не вызывает поиск по вкладкам

### ISSUE THREAD

**Issue by borwi4ok** [camellia-app/camellia#381]
Подсказка на скрине ниже говорит, что при нажатии ctrl+f вызовется поиск по вкладкам
![image](https://user-images.githubusercontent.com/33358994/212564306-4ac376f6-9eab-4fce-9985-f142cfee360b.png)

Фактически вызывается поиск по странице определенный браузером.

воспроизводится на Google Chrome, Win 10

есть вариант взять другое сочетание, как к примеру здесь https://tailwindcss.com/

**Comment by flaksp** [comment]
Проблема известная. Так происходит из-за того, что при открытии новой вкладки в фокусе находится не HTML-документ, а оболочка браузера, поэтому события `keydown` документом не будут перехватываться, пока пользователь не повзаимодейстствует со страницей (например, не кликнет куда-нибудь).

Добавление иного сочетания клавиш, к сожалению, не поможет.
