### ISSUE TITLE
Не открывается расширение при открытии нового таба

### ISSUE THREAD

**Issue by borwi4ok** [camellia-app/camellia#382]
![image](https://user-images.githubusercontent.com/33358994/212776585-564f8fa3-f94a-4954-83c8-25e37e552c1f.png)
![image](https://user-images.githubusercontent.com/33358994/212776597-2822f2b3-9d05-4001-81cf-ed0a537831e8.png)

https://github.com/WICG/view-transitions/blob/main/debugging_overflow_on_images.md

**Comment by flaksp** [comment]
Ошибка из-за того, что папку с расширением перенес или удалил.
