### ISSUE TITLE
Add "Learn more" link to the description of "Send anonymous usage statistics" and "Send error reports" options

### ISSUE THREAD

**Issue by flaksp** [camellia-app/camellia#408]
Currently, there are only two options that responsible for collecting some data about our users:

- "Send anonymous usage statistics"
- "Send error reports"

But most users won't understand what these options do. For that purpose we should add a link to both descriptions to allow our users read our privacy policy.

It should be a link labeled "Learn more" that comes right after the description. In Russian it should be labeled as "Подробнее". This is an example how it should look like:

<img width="686" alt="Screenshot 2023-02-19 at 16 13 09" src="https://user-images.githubusercontent.com/12474739/219950277-9766f1a0-4c76-41f4-bfd1-09334c83f94f.png">

The link should lead to our [Privacy Policy](https://github.com/camellia-app/camellia/wiki/Privacy-Policy) page.

It would be good to add new optional property to the `LabeledTextField` component that will allow us to specify a link, and "Learn more" link should be displayed only if the link property was passed to the component.

**Comment by BleileJustin** [comment]
For this issue, `LabeledTextField` looks like it is only used in the Background option tab. In the Data Collection tab it uses the component `LabeledCheckbox` which has the `Checkbox` and `Paragraph` components as children. Would you like a prop going to `LabeledCheckbox` for the link instead?

**Comment by flaksp** [comment]
> Would you like a prop going to `LabeledCheckbox` for the link instead?

Yeah! I mistyped component name. It should be added to the `LabeledCheckbox`.
