### ISSUE TITLE
Add hints to search dialog

### ISSUE THREAD

**Issue by flaksp** [camellia-app/camellia#409]
Add hints to the bottom of the search dialog.

<img width="810" alt="Screenshot 2023-02-19 at 18 48 46" src="https://user-images.githubusercontent.com/12474739/219958853-1f7df49f-8ada-4045-8d93-f0009557cced.png">

Every time user opens the dialog a random hint should be displayed:

- "You can open search with Ctrl + F or Ctrl + G shortcuts"
- "You may press any character to open search"
- "You can close search with Esc"
- "Press Enter to open first link"

**Comment by BleileJustin** [comment]
From what I understand, I think I'm doing this right.  Ive submitted a pull request for this feature.
